sudo: required
language: node_js
node_js:
  - "10.15.3"
branches:
  only:
    - master
before_install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_API_TOKEN